src/Entity/Album.php
<?php

namespace App\Entity;

use App\Enum\LanguageEnum;
use App\Repository\AlbumRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AlbumRepository::class)]
class Album
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(enumType: LanguageEnum::class)]
    private ?LanguageEnum $language = null;

    #[ORM\ManyToOne(inversedBy: 'albums')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Genre $genre = null;

    #[ORM\ManyToOne(inversedBy: 'albums')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Artist $artist = null;

    /**
     * @var Collection<int, Song>
     */
    #[ORM\OneToMany(targetEntity: Song::class, mappedBy: 'album', orphanRemoval: true)]
    private Collection $songs;

    public function __construct()
    {
        $this->songs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLanguage(): ?LanguageEnum
    {
        return $this->language;
    }

    public function setLanguage(LanguageEnum $language): static
    {
        $this->language = $language;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): static
    {
        $this->artist = $artist;

        return $this;
    }

    /**
     * @return Collection<int, Song>
     */
    public function getSongs(): Collection
    {
        return $this->songs;
    }

    public function addSong(Song $song): static
    {
        if (!$this->songs->contains($song)) {
            $this->songs->add($song);
            $song->setAlbum($this);
        }

        return $this;
    }

    public function removeSong(Song $song): static
    {
        if ($this->songs->removeElement($song)) {
            // set the owning side to null (unless already changed)
            if ($song->getAlbum() === $this) {
                $song->setAlbum(null);
            }
        }

        return $this;
    }

    public function getTotalDuration(): ?string
    {
        $totalDuration = 0;
        foreach ($this->songs as $song) {
            $totalDuration += $song->getDuration();
        }
        $minutes = intdiv($totalDuration, 60);
        $seconds = $totalDuration % 60;
        return "{$minutes}min{$seconds}s";
    }
}

src/Entity/Song.php
<?php

namespace App\Entity;

use App\Enum\LanguageEnum;
use App\Repository\SongRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SongRepository::class)]
class Song
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\ManyToOne(inversedBy: 'songs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Album $album = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'song')]
    #[ORM\JoinColumn(nullable: false)]
    private Collection $comments;

    /**
     * @var Collection<int, Playlist>
     */
    #[ORM\ManyToMany(targetEntity: Playlist::class, mappedBy: 'songs')]
    private Collection $playlists;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private ?array $contributors = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->playlists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): static
    {
        $this->album = $album;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setSong($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getSong() === $this) {
                $comment->setSong(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Playlist>
     */
    public function getPlaylists(): Collection
    {
        return $this->playlists;
    }

    public function addPlaylist(Playlist $playlist): static
    {
        if (!$this->playlists->contains($playlist)) {
            $this->playlists->add($playlist);
            $playlist->addSong($this);
        }

        return $this;
    }

    public function removePlaylist(Playlist $playlist): static
    {
        if ($this->playlists->removeElement($playlist)) {
            $playlist->removeSong($this);
        }

        return $this;
    }

    public function getContributors(): ?array
    {
        return $this->contributors;
    }

    public function setContributors(?array $contributors): static
    {
        $this->contributors = $contributors;

        return $this;
    }

    public function getDurationInMinutes(): ?string
    {
        $minutes = intdiv($this->duration, 60);
        $seconds = $this->duration % 60;
        return "{$minutes}min{$seconds}s";
    }

    public function getAverage(): ?int
    {
        $average = 0;
        foreach($this->comments as $comment) {
            $average += $comment->getNote();
        }
        return $this->comments->count() > 0 ? round($average / $this->comments->count(), 2) : null;
    }
}

src/Form/SongType.php
<?php

namespace App\Form;

use App\Entity\Album;
use App\Entity\Artist;
use App\Entity\Genre;
use App\Entity\Playlist;
use App\Entity\Song;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SongType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('duration')
            ->add('album', EntityType::class, [
                'class' => Album::class,
                'choice_label' => 'id',
            ])
            ->add('playlists', EntityType::class, [
                'class' => Playlist::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Song::class,
        ]);
    }
}

src/Controller/SongController.php
<?php

namespace App\Controller;

use App\Entity\Song;
use App\Form\SongType;
use App\Repository\SongRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\ExpressionLanguage\Expression;

#[Route('/song')]
final class SongController extends AbstractController
{
    #[Route(name: 'all-songs', methods: ['GET'])]
    public function index(SongRepository $songRepository): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_USER")'
        ));

        return $this->render('song/index.html.twig', [
            'songs' => $songRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'song-add', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_ARTIST")'
        ));

        $song = new Song();
        $form = $this->createForm(SongType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($song);
            $entityManager->flush();

            return $this->redirectToRoute('all-songs', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('song/new.html.twig', [
            'song' => $song,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'song-show', methods: ['GET'])]
    public function show(Song $song): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_USER")'
        ));

        return $this->render('song/show.html.twig', [
            'song' => $song,
        ]);
    }

    #[Route('/{id}/edit', name: 'song-edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Song $song, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_ARTIST")'
        ));

        $form = $this->createForm(SongType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('all-songs', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('song/edit.html.twig', [
            'song' => $song,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'song-delete', methods: ['POST'])]
    public function delete(Request $request, Song $song, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_ARTIST")'
        ));

        if ($this->isCsrfTokenValid('delete'.$song->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($song);
            $entityManager->flush();
        }

        return $this->redirectToRoute('all-songs', [], Response::HTTP_SEE_OTHER);
    }
}

templates/song/_delete_form.html.twig
<form method="post" action="{{ path('song-delete', {'id': song.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ song.id) }}">
    <button class="btn">Delete</button>
</form>

templates/song/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Song{% endblock %}

{% block body %}
    <h1>Edit Song</h1>

    {{ include('song/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('all-songs') }}">back to list</a>

    {{ include('song/_delete_form.html.twig') }}
{% endblock %}

templates/song/index.html.twig
{% extends 'base.html.twig' %} {% block title %}Toutes les chansons{% endblock %}
{% block body %}
<h1 class="text-center text-2xl font-extrabold my-5">Toutes les chansons</h1>

<div class="grid grid-cols-4 gap-4 px-6">
  {% for song in songs %}
    {% include './components/song-card.html.twig' %}
  {% else %}
  <span>Aucune chanson trouvé</span>
  {% endfor %}
</div>
{% endblock %}

templates/song/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Song{% endblock %}

{% block body %}
    <h1>Create new Song</h1>

    {{ include('song/_form.html.twig') }}

    <a href="{{ path('all-songs') }}">back to list</a>
{% endblock %}

templates/song/show.html.twig
{% extends 'base.html.twig' %} {% block title %}{{song.title}}{% endblock %} {%
block body %}
<a
  class="text-teal-500 underline font-semibold p-6 mt-6"
  href="{{ path('all-songs') }}"
  >< Retourner à liste</a
>
<div class="flex p-6 justify-start gap-10">
  <img
    src="{{ song.album.image }}"
    alt="{{song.title}}"
    class="w-40 bg-amber-200 rounded-md"
  />
  <div class="w-2/5">
    <h1 class="text-2xl font-extrabold my-5">
      {{song.title|upper}} · {{song.album.artist.name}}
    </h1>
    <ul>
      <li>
        <span class="text-teal-900 font-bold">Durée: </span
        >{{song.getDurationInMinutes()}}
      </li>
      <li>
        <span class="text-teal-900 font-bold">Genre: </span
        >{{song.album.genre.name}}
      </li>
      <li>
        <span class="text-teal-900 font-bold">Langue: </span
        >{{song.album.language.value}}
      </li>
      <li>
        <span class="text-teal-900 font-bold">Date de sortie: </span
        >{{song.album.releaseDate|date('d/m/Y')}}
      </li>
      {% if song.contributors|length > 0 %}
      <li>
        <span class="text-teal-900 font-bold">Contributeurs: </span>
        <ul class="list-disc ml-8">
          {% for contributor in song.contributors %}
          <li>{{contributor}}</li>
          {% endfor %}
        </ul>
      </li>
      {% endif %}
    </ul>
  </div>
</div>
<div class="p-6">
  <h2 class="text-xl text-teal-900 font-bold mb-4">Commentaires 
    {% if song.getAverage() %}
      · Note Moyenne : {{song.getAverage()}}/5
    {% endif %}
  </h2>
  <div class="flex flex-col gap-3 w-3/4">
  {% for comment in song.comments %}
  <div class="px-8 py-2 rounded-lg bg-cyan-200/50 border-2 border-teal-700">
    <span class="text-lg text-teal-700 font-semibold mb-3">
      {{comment.user.name}} {{comment.user.lastName}} · {{comment.note}}/5
    </span>
    <p>{{comment.content}}</p>
  </div>
  {% else %}
  <span>Aucun commentaire</span>
  {% endfor %}
  </div>
</div>
{% endblock %}