src/Entity/Playlist.php
<?php

namespace App\Entity;

use App\Repository\PlaylistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlaylistRepository::class)]
class Playlist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $creation_date = null;

    #[ORM\ManyToOne(inversedBy: 'playlists')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, Song>
     */
    #[ORM\ManyToMany(targetEntity: Song::class, inversedBy: 'playlists')]
    private Collection $songs;

    public function __construct()
    {
        $this->songs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Song>
     */
    public function getSongs(): Collection
    {
        return $this->songs;
    }

    public function addSong(Song $song): static
    {
        if (!$this->songs->contains($song)) {
            $this->songs->add($song);
        }

        return $this;
    }

    public function removeSong(Song $song): static
    {
        $this->songs->removeElement($song);

        return $this;
    }
}

src/Form/PlaylistType.php
<?php

namespace App\Form;

use App\Entity\Playlist;
use App\Entity\Song;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlaylistType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('creation_date', null, [
                'widget' => 'single_text',
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
            ->add('songs', EntityType::class, [
                'class' => Song::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Playlist::class,
        ]);
    }
}

src/Controller/PlaylistController.php
<?php

namespace App\Controller;

use App\Entity\Playlist;
use App\Form\PlaylistType;
use App\Repository\PlaylistRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Core\Security;

#[Route('/playlist')]
final class PlaylistController extends AbstractController
{
    #[Route('/user/{id}', name: 'playlists', methods: ['GET'])]
    public function index(PlaylistRepository $playlistRepository, int $id): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_USER")'
        ));

        return $this->render('playlist/index.html.twig', [
            'playlists' => $playlistRepository->findBy(['user' => $id]),
        ]);
    }

    #[Route('/new', name: 'playlist-add', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_USER")'
        ));

        $playlist = new Playlist();
        $form = $this->createForm(PlaylistType::class, $playlist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($playlist);
            $entityManager->flush();

            return $this->redirectToRoute('playlists', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('playlist/new.html.twig', [
            'playlist' => $playlist,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'playlist-show', methods: ['GET'])]
    public function show(Playlist $playlist): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_USER")'
        ));

        return $this->render('playlist/show.html.twig', [
            'playlist' => $playlist,
        ]);
    }

    #[Route('/{id}/edit', name: 'playlist-edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Playlist $playlist, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_USER")'
        ));

        $form = $this->createForm(PlaylistType::class, $playlist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('playlists', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('playlist/edit.html.twig', [
            'playlist' => $playlist,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'playlist-delete', methods: ['POST'])]
    public function delete(Request $request, Playlist $playlist, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted(new Expression(
            'is_granted("ROLE_USER")'
        ));

        if ($this->isCsrfTokenValid('delete'.$playlist->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($playlist);
            $entityManager->flush();
        }

        return $this->redirectToRoute('playlists', [], Response::HTTP_SEE_OTHER);
    }
}

templates/playlist/_delete_form.html.twig
<form method="post" action="{{ path('playlist-delete', {'id': playlist.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ playlist.id) }}">
    <button class="btn">Delete</button>
</form>

templates/playlist/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/playlist/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Playlist{% endblock %}

{% block body %}
    <h1>Edit Playlist</h1>

    {{ include('playlist/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('playlists') }}">back to list</a>

    {{ include('playlist/_delete_form.html.twig') }}
{% endblock %}

templates/playlist/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Playlist index{% endblock %}

{% block body %}
    <h1>Playlist index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Creation_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for playlist in playlists %}
            <tr>
                <td>{{ playlist.id }}</td>
                <td>{{ playlist.title }}</td>
                <td>{{ playlist.description }}</td>
                <td>{{ playlist.creationDate ? playlist.creationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('playlist-show', {'id': playlist.id}) }}">show</a>
                    <a href="{{ path('playlist-edit', {'id': playlist.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('playlist-add') }}">Create new</a>
{% endblock %}

templates/playlist/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Playlist{% endblock %}

{% block body %}
    <h1>Create new Playlist</h1>

    {{ include('playlist/_form.html.twig') }}

    <a href="{{ path('playlists') }}">back to list</a>
{% endblock %}

templates/playlist/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Playlist{% endblock %}

{% block body %}
    <h1>Playlist</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ playlist.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ playlist.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ playlist.description }}</td>
            </tr>
            <tr>
                <th>Creation_date</th>
                <td>{{ playlist.creationDate ? playlist.creationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('playlists') }}">back to list</a>

    <a href="{{ path('playlist-edit', {'id': playlist.id}) }}">edit</a>

    {{ include('playlist/_delete_form.html.twig') }}
{% endblock %}